- name: Create Apache2 pages
  hosts: webserver
  become: true

  tasks: 
    - name: Create api directory
      file:
        path: /var/www/html/api
        state: directory
        mode: "0755"

    - name: Create front directory
      file:
        path: /var/www/html/front
        state: directory
        mode: "0755"

    - name: Create back directory
      file:
        path: /var/www/html/back
        state: directory
        mode: "0755"
    - name: Copy api.html for api.hei.school
      copy:
        src: /home/sullivan/Sys1-Ansible/api.html
        dest: /var/www/html/api/index.html

    - name: Copy front.html for front.hei.school
      copy:
        src: /home/sullivan/Sys1-Ansible/front.html
        dest: /var/www/html/front/index.html

    - name: Copy back.html for back.hei.school
      copy:
        src: /home/sullivan/Sys1-Ansible/back.html
        dest: /var/www/html/back/index.html
